use_frameworks!

platform :ios, '8.0'

target 'FrameworkTest_Example' do
  pod 'FrameworkTest', :path => '../'

  target 'FrameworkTest_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
